AMQP_URI: amqp://${RABBIT_USER:user}:${RABBIT_PASSWORD:password}@${RABBIT_HOST:localhost}:${RABBIT_PORT:5672}/

DB_URIS: 
  'service_usuario:Base': 'mysql+pymysql://root:password@localhost:3306/abcBolinhas?charset=utf8'

rpc_exchange: 'nameko-rpc'
max_workers: 10
parent_calls_tracked: 10